/*
 * Lab2A2-S19.c
 *
 * Created: 3/2/2019 10:56:00 PM
 * Author : Eric Smith
 */ 
#define F_CPU 1600000000UL
#include <avr/io.h>
#include <util/delay.h>

// LED CONNECTED TO PORTB.2 (D4)
// SWITCH CONNECTED TO PORTC.2
// PINB5 WAS MALFUNCTIONING ON SHIELD, WOULD STAY ON REGARDLESS OF EFFORT TO TURN IT OFF
// UPON TRYING TO RECORD A VIDEO FOR THIS CODE, ATMEL STUDIO DID RECOGNIZE MY XPLAINED MINI BOARD BEING PLUGGED IN

int main(void)
{
    // SET PORTB FOR OUTPUT
	
	DDRB |= (1<<PB2); // SET ONLY THAT LED TO BE ON WHEN NEEDED (AS OUTPUT)
	PORTB |= (1<<PB2); // TURN LED OFF
	
	// SET PORTC FOR INPUT 
	
	DDRC &= (0 << 1);
	PORTC = 0xFF; // ACTIVATES PULL-UP RESISTANCE ON PORTC 
	
	
    while (1) // INFINITE LOOP
    {
		// POLLING
		if (!(PINC & (1<<PINC))) // COMPLIMENT ENTIRE PART, CHECK FOR PIN C FOR A VALUE 1 & THEN COMPLIMENT 
		{
			PORTB &= ~(1<<PB2); // INVERTS LOGIC LEVEL ON PORTB
			_delay_ms(1250); // LED ON FOR 1250 ms
		}
		else
			PORTB |= (1<<PB2);
	}
			return 0;
}

