;
; DA_2A_ASSEMBLY.asm
;
; Created: 3/4/2019 8:31:33 PM
; Author : Eric Smith 

; 60% DC and 0.725 sec period (0.725 * .60 = .435) 
; (0.725 - 0.435 = 0.290)
; (ATMEGA328P XPLAINED MINI BOARD WOULD NOT HOOK WITH ATMEL STUDIO 7, POSSIBLY BROKEN)

.ORG 0
LDI R16, 4 ; PB2 REPRESENTATION
OUT DDRB, R16 ; ENABLE PB2 AS OUTPUT
LDI R17, 4 ; CAN SET OR RESET PB2
LDI R20, 5 ; PRESCALER CLOCK AT 1024 
STS TCCR1B, R20

begin:

LDI R20, 0x00 ; RESETTING COUNTER TO 0
STS TCNT1H, R20
STS TCNT1L, R20

RCALL delay ; CALLING TIMER TO WAIT FOR 435 ms
EOR R17, R16 ; XOR TO TOGGLE LED
OUT PORTB, R17
LDI R20, 0x00 ; RESET COUNTER TO 0
STS TCNT1H, R20
STS TCNT1L, R20

RCALL delay2 ; CALL TIMER TO WAIT FOR 290 ms
EOR R17, R16 ; XOR TO TOGGLE LED AGAIN
OUT PORTB, R17
RJMP begin ; MAIN LOOP IS REPEATED

delay:

LDS R29, TCNT1H ; LOADING UPPER BIT OF COUNTER TO R29
LDS R28, TCNT1L ; LOADING LOWER BIT OF COUNTER TO R28
CPI R28, 0x8C ; COMPARING IF LOWER 8 BITS OF TIMER IS 0x8C
BRSH body ; IF LOWER BITS OF TIMER HAVE REACHED DESIRED AMOUNT, CHECK UPPER BITS
RJMP delay ; IF NOT, KEEP CHECKING LOWER BITS

body:

CPI R29, 0x1A ; CHECK TO SEE IF UPPER TIMER BITS HAVE REACHED THE DESIRED VALUE 
BRLT delay ; IF NOT, RECHECK LOWER BITS
RET ; ONCE THE TIMER HAS REACHED THE DESIRED VALUE, TOGGLE THE LED

delay2:

LDS R29, TCNT1H ; LOADING UPPER BIT OF COUNTER TO R29
LDS R28, TCNT1L ; LOADING LOWER BIT OF COUNTER TO R28
CPI R28, 0xB2 ; COMPARING IF LOWER 8 BITS OF TIMER IS 0xB2
BRSH body2 ; IF LOWER BITS OF TIMER HAVE REACHED DESIRED AMOUNT, CHECK THE UPPER BITS
RJMP delay2 ; IF NOT, KEEP CHECKING LOWER BITS 

body2:

CPI R29, 0x11 ; CHECK TO SEE IF UPPER TIMER BITS HAVE REACHED THE DESIRED VALUE
BRLT delay2 ; IF NOT, RECHECK LOWER BITS
RET ; ONCE TIMER HAS REACHED THE DESIRED VALUE, TOGGLE THE LED



